// ================================================================
//  StickerVersz — stickers.js
//  THIS IS THE ONLY FILE YOU NEED TO EDIT to manage stickers.
// ================================================================
//
//  HOW TO ADD A STICKER — copy any line and change the values:
//
//    { id: 'AN-016', name: 'My Sticker', category: 'anime', emoji: '⭐' },
//
//  ADD A "NEW" BADGE:
//    { ..., isNew: true },
//
//  USE YOUR OWN IMAGE (put the file in the images/ folder):
//    { ..., image: 'images/my-sticker.png' },
//
//  CHANGE THE PRICE (default is 3 MAD):
//    { ..., price: 2 },
//
//  AVAILABLE CATEGORIES:
//    anime · kpop · gaming · sports · movies · music · study · manga · cars · memes · quotes · series · kdrama · others
//
// ================================================================

const STICKERS = [

  // ── ANIME ────────────────────────────────────────────────────
  { id: 'AN-001', name: 'turbo granny',      category: 'anime',  emoji: '🔵', image: 'images/turbo granny.png', isNew: true, price: 3   },
  { id: 'AN-002', name: 'killua', category: 'anime', emoji: '🦊', image: 'images/killua.png', isNew: true, price: 3  },
  { id: 'AN-003', name: 'Monkey D. Luffy',  category: 'anime',  emoji: '🔴' ,image: 'images/monkey d luffy.png', isNew: true, price: 3  },
  { id: 'AN-004', name: 'titan', category: 'anime', emoji: '🦊', image: 'images/titan.png', isNew: true, price: 3   },
  { id: 'AN-005', name: 'my hero academia', category: 'anime', emoji: '🦊', image: 'images/my hero academia.png', isNew: true, price: 3   },
  { id: 'AN-006', name: 'one piece', category: 'anime', emoji: '🦊', image: 'images/one piece.png', isNew: true, price: 3  },
  { id: 'AN-007', name: 'shigaraki', category: 'anime', emoji: '🦊', image: 'images/shigaraki.png', isNew: true, price: 3  },
  { id: 'AN-008', name: 'fire force', category: 'anime', emoji: '🦊', image: 'images/fire force.png', isNew: true, price: 3    },
  { id: 'AN-009', name: 'jjk', category: 'anime', emoji: '🦊', image: 'images/jjk.png', isNew: true, price: 3    },
  { id: 'AN-010', name: 'kaiju no 8', category: 'anime', emoji: '🦊', image: 'images/kaijo no 8.png', isNew: true, price: 3   },
  { id: 'AN-011', name: 'makima', category: 'anime', emoji: '🦊', image: 'images/makima.png',  isNew: true, price: 3 },
  { id: 'AN-012', name: 'all might', category: 'anime', emoji: '🦊', image: 'images/all might.png', isNew: true, price: 3  },
  { id: 'AN-013', name: 'aot', category: 'anime', emoji: '🦊', image: 'images/aot.png', isNew: true, price: 3  },
  { id: 'AN-014', name: 'bakugo', category: 'anime', emoji: '🦊', image: 'images/bakugo.png', isNew: true, price: 3  },
  { id: 'AN-015', name: 'chainsaw man', category: 'anime', emoji: '🦊', image: 'images/chainsaw man.png', isNew: true, price: 3   },
  { id: 'AN-016', name: 'dan da dan', category: 'anime', emoji: '🦊', image: 'images/dan da dan.png', isNew: true, price: 3   },
  { id: 'AN-017', name: 'dr stone', category: 'anime', emoji: '🦊', image: 'images/dr stone.png', isNew: true, price: 3  },

  // ── K-POP ────────────────────────────────────────────────────
  { id: 'KP-001', name: 'BTS', category: 'kpop', emoji: '🦊', image: 'images/kp001.png', isNew: true, price: 3  },
  { id: 'KP-002', name: 'STRAY KIDS', category: 'kpop', emoji: '🦊', image: 'images/kp002.png', isNew: true, price: 3  },
  { id: 'KP-003', name: 'HAN JISUNG', category: 'kpop', emoji: '🦊', image: 'images/kp003.png', isNew: true, price: 3  }, 
  { id: 'KP-004', name: 'BTS', category: 'kpop', emoji: '🦊', image: 'images/kp006.png', isNew: true, price: 3  }, 
  { id: 'KP-005', name: 'BTS', category: 'kpop', emoji: '🦊', image: 'images/kp007.png', isNew: true, price: 3  },
  { id: 'KP-006', name: 'baby monster', category: 'kpop', emoji: '🦊', image: 'images/kp008.png', isNew: true, price: 3  },
  { id: 'KP-007', name: '', category: 'kpop', emoji: '🦊', image: 'images/kp009.png', isNew: true, price: 3  },
  { id: 'KP-008', name: '', category: 'kpop', emoji: '🦊', image: 'images/kp010.png', isNew: true, price: 3  },
  { id: 'KP-009', name: '', category: 'kpop', emoji: '🦊', image: 'images/kp011.png', isNew: true, price: 3  },
  { id: 'KP-010', name: '', category: 'kpop', emoji: '🦊', image: 'images/kp012.png', isNew: true, price: 3  },
 
  // ── GAMING ───────────────────────────────────────────────────
  { id: 'GA-001', name: 'MARIO PLANT', category: 'gaming', emoji: '🦊', image: 'images/g002.png', isNew: true, price: 3  },
  { id: 'GA-002', name: 'GAMERS DONT DIE', category: 'gaming', emoji: '🦊', image: 'images/g003.png', isNew: true, price: 3  },  
  { id: 'GA-003', name: 'MUSHROOM', category: 'gaming', emoji: '🦊', image: 'images/g004.png', isNew: true, price: 3  },   
  { id: 'GA-004', name: 'PAC MAN', category: 'gaming', emoji: '🦊', image: 'images/g005.png', isNew: true, price: 3  },  
  { id: 'GA-005', name: 'ZOMBIE', category: 'gaming', emoji: '🦊', image: 'images/g006.png', isNew: true, price: 3  },  
  { id: 'GA-006', name: 'CONTROLLER BUTTONS', category: 'gaming', emoji: '🦊', image: 'images/g007.png', isNew: true, price: 3  },  
  { id: 'GA-007', name: 'YOSHI', category: 'gaming', emoji: '🦊', image: 'images/g008.png', isNew: true, price: 3  },  
  { id: 'GA-008', name: 'GAME MODE ON', category: 'gaming', emoji: '🦊', image: 'images/g009.png', isNew: true, price: 3  },  
  { id: 'GA-009', name: 'PLAY STATION', category: 'gaming', emoji: '🦊', image: 'images/g010.png', isNew: true, price: 3  },  
  { id: 'GA-010', name: 'HEARTS', category: 'gaming', emoji: '🦊', image: 'images/g011.png', isNew: true, price: 3  },  
  { id: 'GA-011', name: 'SEGA', category: 'gaming', emoji: '🦊', image: 'images/g012.png', isNew: true, price: 3  },  
  { id: 'GA-012', name: 'MARIO STAR', category: 'gaming', emoji: '🦊', image: 'images/g013.png', isNew: true, price: 3  },  
  { id: 'GA-013', name: 'STREET FIGHTER', category: 'gaming', emoji: '🦊', image: 'images/g014.png', isNew: true, price: 3  },  
  { id: 'GA-014', name: 'HOLLOW KNIGHT', category: 'gaming', emoji: '🦊', image: 'images/g015.png', isNew: true, price: 3  },  
  { id: 'GA-015', name: 'CRASH', category: 'gaming', emoji: '🦊', image: 'images/g016.png', isNew: true, price: 3  },  
  { id: 'GA-016', name: 'GB CONTROLLER', category: 'gaming', emoji: '🦊', image: 'images/g017.png', isNew: true, price: 3  },   
  
  // ── SPORTS ───────────────────────────────────────────────────
  { id: 'SP-001', name: 'FC BARCELONA', category: 'sports', emoji: '🦊', image: 'images/sp001.png', isNew: true, price: 3  },
  { id: 'SP-002', name: 'RAJA', category: 'sports', emoji: '🦊', image: 'images/sp002.png', isNew: true, price: 3  },
  { id: 'SP-003', name: 'EAGLES', category: 'sports', emoji: '🦊', image: 'images/sp003.png', isNew: true, price: 3  },
  { id: 'SP-004', name: 'WIDAD', category: 'sports', emoji: '🦊', image: 'images/sp004.png', isNew: true, price: 3  },
  { id: 'SP-005', name: 'WINS05', category: 'sports', emoji: '🦊', image: 'images/sp005.png', isNew: true, price: 3  },
  { id: 'SP-006', name: 'WDC TROPHY', category: 'sports', emoji: '🦊', image: 'images/sp006.png', isNew: true, price: 3  },
  { id: 'SP-007', name: 'REAL MADRID', category: 'sports', emoji: '🦊', image: 'images/sp007.png', isNew: true, price: 3  },
  { id: 'SP-008', name: 'MANCHESTER UNITED', category: 'sports', emoji: '🦊', image: 'images/sp008.png', isNew: true, price: 3  },
  { id: 'SP-009', name: 'MANCHESTER CITY', category: 'sports', emoji: '🦊', image: 'images/sp009.png', isNew: true, price: 3  },
  { id: 'SP-010', name: 'EAGLES', category: 'sports', emoji: '🦊', image: 'images/sp010.png', isNew: true, price: 3  },
  
  // ── MOVIES ───────────────────────────────────────────────────
  { id: 'MV-001', name: 'SPIDER MAN', category: 'movies', emoji: '🦊', image: 'images/mo001.png', isNew: true, price: 3  },
  { id: 'MV-002', name: 'SPIDER MAN', category: 'movies', emoji: '🦊', image: 'images/mo002.png', isNew: true, price: 3  },
  { id: 'MV-003', name: 'SPIDER MAN', category: 'movies', emoji: '🦊', image: 'images/mo003.png', isNew: true, price: 3  },
  // ── MUSIC ────────────────────────────────────────────────────
  { id: 'MU-001', name: 'AC DC', category: 'music', emoji: '🦊', image: 'images/ac dc.png', isNew: true, price: 3  },
  { id: 'MU-002', name: 'arctic monkeys', category: 'music', emoji: '🦊', image: 'images/arctic monkeys.png', isNew: true, price: 3  },
  { id: 'MU-003', name: 'Black Sabath', category: 'music', emoji: '🦊', image: 'images/black sabath.png', isNew: true, price: 3  },
  { id: 'MU-004', name: 'Doors', category: 'music', emoji: '🦊', image: 'images/doors.png', isNew: true, price: 3  },
  { id: 'MU-005', name: 'Doors', category: 'music', emoji: '🦊', image: 'images/doors1.png', isNew: true, price: 3  },
  { id: 'MU-006', name: 'Eminem', category: 'music', emoji: '🦊', image: 'images/eminem.png', isNew: true, price: 3  },
  { id: 'MU-007', name: 'Gorillaz', category: 'music', emoji: '🦊', image: 'images/gorillaz.png', isNew: true, price: 3  },
  { id: 'MU-008', name: 'Guns n Roses', category: 'music', emoji: '🦊', image: 'images/guns n roses.png', isNew: true, price: 3  },
  { id: 'MU-009', name: 'KISS', category: 'music', emoji: '🦊', image: 'images/kiss.png', isNew: true, price: 3  },
  { id: 'MU-010', name: 'LED ZEPPELIN', category: 'music', emoji: '🦊', image: 'images/led zeppelin.png', isNew: true, price: 3  },
  { id: 'MU-011', name: 'LINKIN PARK', category: 'music', emoji: '🦊', image: 'images/linkin park.png', isNew: true, price: 3  },
  { id: 'MU-012', name: 'MEGADETH', category: 'music', emoji: '🦊', image: 'images/megadeth.png', isNew: true, price: 3  },
  { id: 'MU-013', name: 'NIRVANA', category: 'music', emoji: '🦊', image: 'images/nirvana.png', isNew: true, price: 3  },
  { id: 'MU-014', name: 'OZZY OSBURNE', category: 'music', emoji: '🦊', image: 'images/ozzy osburne.png', isNew: true, price: 3  },
  { id: 'MU-015', name: 'PEARL JAM', category: 'music', emoji: '🦊', image: 'images/pearl jam.png', isNew: true, price: 3  },
  { id: 'MU-016', name: 'PINK FLOYD', category: 'music', emoji: '🦊', image: 'images/pink floyd 1.png', isNew: true, price: 3  },
  { id: 'MU-017', name: 'PINK FLOYD', category: 'music', emoji: '🦊', image: 'images/pink floyd.png', isNew: true, price: 3  },
  { id: 'MU-018', name: 'ROCK AND ROLL', category: 'music', emoji: '🦊', image: 'images/rock and roll.png', isNew: true, price: 3  },
  { id: 'MU-019', name: 'DUA LIPA WDC26', category: 'music', emoji: '🦊', image: 'images/mu001.png', isNew: true, price: 3  },
  { id: 'MU-020', name: 'THE ROLLING STONES', category: 'music', emoji: '🦊', image: 'images/mu002.png', isNew: true, price: 3  }, 
  { id: 'MU-021', name: 'MICHAEL JACKSON', category: 'music', emoji: '🦊', image: 'images/mu003.png', isNew: true, price: 3  }, 
  { id: 'MU-022', name: 'MADONNA', category: 'music', emoji: '🦊', image: 'images/mu004.png', isNew: true, price: 3  }, 
  { id: 'MU-023', name: 'MAYHEM LADY GAGA', category: 'music', emoji: '🦊', image: 'images/mu005.png', isNew: true, price: 3  }, 
  { id: 'MU-024', name: 'I LOVE LADY GAGA', category: 'music', emoji: '🦊', image: 'images/mu006.png', isNew: true, price: 3  }, 
  { id: 'MU-025', name: 'DUA LIPA', category: 'music', emoji: '🦊', image: 'images/mu007.png', isNew: true, price: 3  }, 
  { id: 'MU-026', name: 'TAYLOR SWIFT', category: 'music', emoji: '🦊', image: 'images/mu008.png', isNew: true, price: 3  },
  // ── STUDY ────────────────────────────────────────────────────
  { id: 'ST-001', name: 'ANNIA DONT WANT TO STUDY', category: 'study', emoji: '🦊', image: 'images/AN001.png', isNew: true, price: 3  },
  { id: 'ST-002', name: 'A VERY TIRED STUDENT', category: 'study', emoji: '🦊', image: 'images/AN002.png', isNew: true, price: 3  },
  { id: 'ST-003', name: 'CAT', category: 'study', emoji: '🦊', image: 'images/AN003.png', isNew: true, price: 3  },
  { id: 'ST-004', name: 'ADORABLE FUNNY', category: 'study', emoji: '🦊', image: 'images/AN004.png', isNew: true, price: 3  },
  { id: 'ST-005', name: 'BAKUGO STUDY', category: 'study', emoji: '🦊', image: 'images/AN005.png', isNew: true, price: 3  },
  { id: 'ST-006', name: 'DAILY MOTIVATION', category: 'study', emoji: '🦊', image: 'images/AN006.png', isNew: true, price: 3  },
  { id: 'ST-007', name: 'GRADUATION HAT', category: 'study', emoji: '🦊', image: 'images/AN007.png', isNew: true, price: 3  },
  { id: 'ST-008', name: 'FOCUS MODE', category: 'study', emoji: '🦊', image: 'images/AN008.png', isNew: true, price: 3  },
  { id: 'ST-009', name: 'FUNNY PANDA', category: 'study', emoji: '🦊', image: 'images/AN009.png', isNew: true, price: 3  },
  { id: 'ST-010', name: 'FUNNY SCIENCE', category: 'study', emoji: '🦊', image: 'images/AN010.png', isNew: true, price: 3  },
  { id: 'ST-011', name: 'BOOKS', category: 'study', emoji: '🦊', image: 'images/AN011.png', isNew: true, price: 3  },
  { id: 'ST-012', name: 'GHOST', category: 'study', emoji: '🦊', image: 'images/AN012.png', isNew: true, price: 3  },
  { id: 'ST-013', name: 'SKELETON ', category: 'study', emoji: '🦊', image: 'images/AN013.png', isNew: true, price: 3  },
  { id: 'ST-014', name: 'TIRED MATH STUDENT', category: 'study', emoji: '🦊', image: 'images/AN014.png', isNew: true, price: 3  },
  { id: 'ST-015', name: 'IM THINKING', category: 'study', emoji: '🦊', image: 'images/AN015.png', isNew: true, price: 3  },
  { id: 'ST-016', name: 'SUCCES', category: 'study', emoji: '🦊', image: 'images/AN016.png', isNew: true, price: 3  },
  { id: 'ST-017', name: 'SPONGE BOB', category: 'study', emoji: '🦊', image: 'images/AN017.png', isNew: true, price: 3  },
  { id: 'ST-018', name: 'ONE MORE CHAPTER', category: 'study', emoji: '🦊', image: 'images/AN018.png', isNew: true, price: 3  },
  { id: 'ST-019', name: 'NOTES', category: 'study', emoji: '🦊', image: 'images/AN019.png', isNew: true, price: 3  },
  { id: 'ST-020', name: 'NEUROSCIENCE', category: 'study', emoji: '🦊', image: 'images/AN020.png', isNew: true, price: 3  },
  { id: 'ST-021', name: 'SAILOR MOON FUNNY', category: 'study', emoji: '🦊', image: 'images/AN021.png', isNew: true, price: 3  },
  { id: 'ST-022', name: 'SNOOPY', category: 'study', emoji: '🦊', image: 'images/AN022.png', isNew: true, price: 3  },
  { id: 'ST-023', name: 'ANNIA FUNNY', category: 'study', emoji: '🦊', image: 'images/AN023.png', isNew: true, price: 3  },
  { id: 'ST-024', name: 'SKELETON HOLDING BOOKS', category: 'study', emoji: '🦊', image: 'images/AN024.png', isNew: true, price: 3  },
  { id: 'ST-025', name: 'BRAIN', category: 'study', emoji: '🦊', image: 'images/AN025.png', isNew: true, price: 3  },
  { id: 'ST-026', name: 'FUNNY DUCK', category: 'study', emoji: '🦊', image: 'images/AN026.png', isNew: true, price: 3  },
  { id: 'ST-027', name: 'STUDY TIME', category: 'study', emoji: '🦊', image: 'images/AN027.png', isNew: true, price: 3  },
  { id: 'ST-028', name: 'HELLO KITTY', category: 'study', emoji: '🦊', image: 'images/AN028.png', isNew: true, price: 3  },
  // ── MANGA ────────────────────────────────────────────────────
  { id: 'MG-001', name: '', category: 'manga', emoji: '🦊', image: 'images/ma001.png', isNew: true, price: 3  },
  { id: 'MG-002', name: '', category: 'manga', emoji: '🦊', image: 'images/ma002.png', isNew: true, price: 3  },
  { id: 'MG-003', name: '', category: 'manga', emoji: '🦊', image: 'images/ma003.png', isNew: true, price: 3  },
  { id: 'MG-004', name: '', category: 'manga', emoji: '🦊', image: 'images/ma004.png', isNew: true, price: 3  },
  { id: 'MG-005', name: '', category: 'manga', emoji: '🦊', image: 'images/ma005.png', isNew: true, price: 3  },
  { id: 'MG-006', name: '', category: 'manga', emoji: '🦊', image: 'images/ma006.png', isNew: true, price: 3  },
  { id: 'MG-007', name: '', category: 'manga', emoji: '🦊', image: 'images/ma007.png', isNew: true, price: 3  },
  { id: 'MG-008', name: '', category: 'manga', emoji: '🦊', image: 'images/ma008.png', isNew: true, price: 3  },
  { id: 'MG-009', name: '', category: 'manga', emoji: '🦊', image: 'images/ma009.png', isNew: true, price: 3  },
  { id: 'MG-010', name: '', category: 'manga', emoji: '🦊', image: 'images/ma010.png', isNew: true, price: 3  },
  
  // ── CARS ─────────────────────────────────────────────────────
  { id: 'CR-001', name: 'BMW M', category: 'cars', emoji: '🦊', image: 'images/c001.png', isNew: true, price: 3  },
  { id: 'CR-002', name: 'LECLERC FERRARI RADIO', category: 'cars', emoji: '🦊', image: 'images/c002.png', isNew: true, price: 3  },
  { id: 'CR-003', name: 'FLAGS', category: 'cars', emoji: '🦊', image: 'images/c003.png', isNew: true, price: 3  },
  { id: 'CR-004', name: 'BOX BOX', category: 'cars', emoji: '🦊', image: 'images/c004.png', isNew: true, price: 3  },
  { id: 'CR-005', name: 'FERRARI', category: 'cars', emoji: '🦊', image: 'images/c005.png', isNew: true, price: 3  },
  { id: 'CR-006', name: 'MERCEDES BENZ', category: 'cars', emoji: '🦊', image: 'images/c006.png', isNew: true, price: 3  },
  { id: 'CR-007', name: 'MUSTANG', category: 'cars', emoji: '🦊', image: 'images/c007.png', isNew: true, price: 3  },
  { id: 'CR-008', name: 'RS', category: 'cars', emoji: '🦊', image: 'images/c008.png', isNew: true, price: 3  },
  { id: 'CR-009', name: 'F1 FERRARI CAR', category: 'cars', emoji: '🦊', image: 'images/c009.png', isNew: true, price: 3  },
  { id: 'CR-010', name: 'AMG', category: 'cars', emoji: '🦊', image: 'images/c010.png', isNew: true, price: 3  },
  // ── MEMES ────────────────────────────────────────────────────
  { id: 'ME-001', name: '', category: 'memes', emoji: '🦊', image: 'images/me001.png', isNew: true, price: 3  },
  { id: 'ME-002', name: '', category: 'memes', emoji: '🦊', image: 'images/me002.png', isNew: true, price: 3  },
  { id: 'ME-003', name: '', category: 'memes', emoji: '🦊', image: 'images/me003.png', isNew: true, price: 3  },
  { id: 'ME-004', name: '', category: 'memes', emoji: '🦊', image: 'images/me004.png', isNew: true, price: 3  },
  { id: 'ME-005', name: '', category: 'memes', emoji: '🦊', image: 'images/me005.png', isNew: true, price: 3  },
  { id: 'ME-006', name: '', category: 'memes', emoji: '🦊', image: 'images/me006.png', isNew: true, price: 3  },
  { id: 'ME-007', name: '', category: 'memes', emoji: '🦊', image: 'images/me007.png', isNew: true, price: 3  },
  { id: 'ME-008', name: '', category: 'memes', emoji: '🦊', image: 'images/me008.png', isNew: true, price: 3  },
  { id: 'ME-009', name: '', category: 'memes', emoji: '🦊', image: 'images/me009.png', isNew: true, price: 3  },
  { id: 'ME-010', name: '', category: 'memes', emoji: '🦊', image: 'images/me010.png', isNew: true, price: 3  },
  
  // ── QUOTES ───────────────────────────────────────────────────
  { id: 'QT-001', name: 'FUNNY QUOTE', category: 'quotes', emoji: '🦊', image: 'images/q001.png', isNew: true, price: 3  },
  { id: 'QT-002', name: 'I DONT CARE', category: 'quotes', emoji: '🦊', image: 'images/q002.png', isNew: true, price: 3  },

  // ── SERIES ───────────────────────────────────────────────────
  { id: 'SR-001', name: 'STRANGER THINGS', category: 'series', emoji: '🦊', image: 'images/se001.png', isNew: true, price: 3  },
 
  // ── K-DRAMA ──────────────────────────────────────────────────
  { id: 'KD-001', name: 'Crash Landing on You', category: 'kdrama', emoji: '🪂', isNew: true },
  { id: 'KD-002', name: 'Goblin',            category: 'kdrama', emoji: '🕯️', isNew: true  },
  { id: 'KD-003', name: 'Itaewon Class',     category: 'kdrama', emoji: '🍺'               },
  { id: 'KD-004', name: 'Vincenzo',          category: 'kdrama', emoji: '🌹', isNew: true  },
  { id: 'KD-005', name: 'The Glory',         category: 'kdrama', emoji: '✨', isNew: true  },
  { id: 'KD-006', name: 'Business Proposal', category: 'kdrama', emoji: '💼'               },
  { id: 'KD-007', name: 'Twenty Five Twenty One', category: 'kdrama', emoji: '🤸'          },
  { id: 'KD-008', name: 'My Love From the Star', category: 'kdrama', emoji: '⭐', isNew: true },
  { id: 'KD-009', name: 'Strong Woman Do Bong-soon', category: 'kdrama', emoji: '💪'       },
  { id: 'KD-010', name: 'Extraordinary Woo', category: 'kdrama', emoji: '🐳', isNew: true  },

  // ── CARTOON ──────────────────────────────────────────────────
  { id: 'CT-001', name: 'GUMBALL', category: 'cartoon', emoji: '🦊', image: 'images/ca001.png', isNew: true, price: 3  },
  { id: 'CT-002', name: 'BIMO', category: 'cartoon', emoji: '🦊', image: 'images/ca002.png', isNew: true, price: 3  },
  { id: 'CT-003', name: 'MCQUEEN', category: 'cartoon', emoji: '🦊', image: 'images/ca003.png', isNew: true, price: 3  },
  { id: 'CT-004', name: 'GENGAR', category: 'cartoon', emoji: '🦊', image: 'images/ca004.png', isNew: true, price: 3  },
  { id: 'CT-005', name: 'JOHNY', category: 'cartoon', emoji: '🦊', image: 'images/ca005.png', isNew: true, price: 3  },
  { id: 'CT-006', name: 'LEMONGRAB', category: 'cartoon', emoji: '🦊', image: 'images/ca006.png', isNew: true, price: 3  },
  { id: 'CT-007', name: 'GUMBALL', category: 'cartoon', emoji: '🦊', image: 'images/ca007.png', isNew: true, price: 3  },
  { id: 'CT-008', name: 'SPONGEBOOB AND PATRICK', category: 'cartoon', emoji: '🦊', image: 'images/ca008.png', isNew: true, price: 3  },
  { id: 'CT-009', name: 'PINK PANTHER', category: 'cartoon', emoji: '🦊', image: 'images/ca009.png', isNew: true, price: 3  },
  { id: 'CT-010', name: 'MUSCLE MAN', category: 'cartoon', emoji: '🦊', image: 'images/ca010.png', isNew: true, price: 3  },
  { id: 'CT-011', name: 'RICK ', category: 'cartoon', emoji: '🦊', image: 'images/ca011.png', isNew: true, price: 3  },
  { id: 'CT-012', name: 'POWERPUFF GIRLS', category: 'cartoon', emoji: '🦊', image: 'images/ca012.png', isNew: true, price: 3  },
  { id: 'CT-013', name: 'JAKE', category: 'cartoon', emoji: '🦊', image: 'images/ca013.png', isNew: true, price: 3  },
  { id: 'CT-014', name: 'TEEN TITANS GO', category: 'cartoon', emoji: '🦊', image: 'images/ca014.png', isNew: true, price: 3  },
  { id: 'CT-015', name: 'FINN AND JAKE AND BIMO', category: 'cartoon', emoji: '🦊', image: 'images/ca015.png', isNew: true, price: 3  },
  { id: 'CT-016', name: 'SPONGE BOB', category: 'cartoon', emoji: '🦊', image: 'images/ca016.png', isNew: true, price: 3  },
  { id: 'CT-017', name: 'GRAVITY FALLS', category: 'cartoon', emoji: '🦊', image: 'images/ca017.png', isNew: true, price: 3  },
  { id: 'CT-018', name: 'SUMOZSKI', category: 'cartoon', emoji: '🦊', image: 'images/ca018.png', isNew: true, price: 3  },
  { id: 'CT-019', name: 'PLANKTON', category: 'cartoon', emoji: '🦊', image: 'images/ca019.png', isNew: true, price: 3  },
  { id: 'CT-020', name: 'PIZZA RICK', category: 'cartoon', emoji: '🦊', image: 'images/ca020.png', isNew: true, price: 3  },
  { id: 'CT-021', name: 'SNORLAX', category: 'cartoon', emoji: '🦊', image: 'images/ca021.png', isNew: true, price: 3  },
  { id: 'CT-022', name: 'REGULAR SHOW', category: 'cartoon', emoji: '🦊', image: 'images/ca022.png', isNew: true, price: 3  },
  { id: 'CT-023', name: 'PICKLE RICK', category: 'cartoon', emoji: '🦊', image: 'images/ca023.png', isNew: true, price: 3  },

  // ── OTHERS ───────────────────────────────────────────────────
  { id: 'OT-001', name: 'CAT', category: 'others', emoji: '🦊', image: 'images/ot001.png', isNew: true, price: 3  },
  { id: 'OT-002', name: 'DORITOS', category: 'others', emoji: '🦊', image: 'images/ot002.png', isNew: true, price: 3  },
  { id: 'OT-003', name: 'MADE IN JAPAN', category: 'others', emoji: '🦊', image: 'images/ot003.png', isNew: true, price: 3  },
  { id: 'OT-004', name: 'OVERTHINKERS CLUB', category: 'others', emoji: '🦊', image: 'images/ot004.png', isNew: true, price: 3  }, 
  { id: 'OT-005', name: 'CUTE', category: 'others', emoji: '🦊', image: 'images/ot005.png', isNew: true, price: 3  },
  { id: 'OT-006', name: 'LIME', category: 'others', emoji: '🦊', image: 'images/ot006.png', isNew: true, price: 3  },
  { id: 'OT-007', name: 'FLOWER', category: 'others', emoji: '🦊', image: 'images/ot007.png', isNew: true, price: 3  },
  { id: 'OT-008', name: 'PRINGLES', category: 'others', emoji: '🦊', image: 'images/ot008.png', isNew: true, price: 3  },
  { id: 'OT-009', name: 'SANTA CRUZ', category: 'others', emoji: '🦊', image: 'images/ot009.png', isNew: true, price: 3  },
  { id: 'OT-010', name: 'MONSTER', category: 'others', emoji: '🦊', image: 'images/ot010.png', isNew: true, price: 3  },
  { id: 'OT-011', name: 'COCA COLA', category: 'others', emoji: '🦊', image: 'images/ot011.png', isNew: true, price: 3  },
  { id: 'OT-012', name: 'CUTE FIRE', category: 'others', emoji: '🦊', image: 'images/ot012.png', isNew: true, price: 3  },
  { id: 'OT-013', name: 'WARNING', category: 'others', emoji: '🦊', image: 'images/ot013.png', isNew: true, price: 3  },
  { id: 'OT-014', name: 'STRAWBERRY MILK', category: 'others', emoji: '🦊', image: 'images/ot014.png', isNew: true, price: 3  },
  { id: 'OT-015', name: 'FUCK OFF', category: 'others', emoji: '🦊', image: 'images/ot015.png', isNew: true, price: 3  },
  { id: 'OT-016', name: 'SUSHI', category: 'others', emoji: '🦊', image: 'images/ot016.png', isNew: true, price: 3  },
  { id: 'OT-017', name: 'TRASHER', category: 'others', emoji: '🦊', image: 'images/ot017.png', isNew: true, price: 3  },
];

